cloudforet-io/console-api

- src/controllers/add-ons/page-schema/identityServiceAccount/default-schema/details.json.tmpl
- 서비스 어카운트의 Page Schema 변경 (태그 추가)
> feat: change page schema

- src/controllers/inventory/cloud-service-tag/index.ts
- src/routes/inventory/cloud-service-tag.ts
- src/routes/inventory/index.ts
- inventory의 CloudServiceTag API 추가
> feat: add inventory.CloudServiceTag APIs

- src/controllers/add-ons/autocomplete/distinct.ts
> feat: temporary code for autocomplete

- src/controllers/add-ons/favorite/index.ts
- src/controllers/add-ons/favorite/order-list/index.ts
- src/controllers/add-ons/favorite/order-list/type.ts
- src/controllers/add-ons/favorite/type.ts
- src/controllers/add-ons/recent/type.ts
- src/routes/add-ons/favorite.ts
- add `DASHBOARD` type to favorite, recent api
- add `order-list/get` and `order-list/set` api to favorite
> feat(favorite): add `order-list/get` and `order-list/set` api

- src/controllers/add-ons/autocomplete/distinct.ts
- src/controllers/add-ons/autocomplete/resource.ts
- Cloud Service의 Tag에 대한 자동 완성 코드 개선
> Refactor Autocomplete

- src/controllers/add-ons/autocomplete/distinct.ts
- `cost_analysis.Cost`의 `tags`와 `additional_info`에 대한 자동완성 시 성능 개선
> refactor: refactor autocomplete in cost_analysis.Cost

- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/search.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/search.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json
- src/lib/grpc-client/proto/query.proto
- Cloud Service와 Server의 Page Schema 변경
- Protobuf 관련 버그 수정
> Change Page Schema and Fix Bugs

- src/lib/grpc-client/proto/query.proto
- AnalyzeQuery의 Message Spec이 변경되어 코드 반영
> Change Message Type

- src/controllers/add-ons/autocomplete/distinct.ts
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json
- 서버 스키마에서 사용하지 않는 필드 제거 (`launched_at`)
- 린트 수정
> Change Schema and Lint

- src/lib/grpc-client/proto/query.proto
- API의 query.proto가 변경됨에 따른 코드 변경
> refactor: change query.proto

- src/controllers/add-ons/autocomplete/distinct.ts
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/search.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/search.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json
- 클라우드 서비스의 스키마 변경
- 클라우드 서비스의 자동완성 로직 변경
> Change Cloud Service APIs

- src/lib/grpc-client/proto/query.proto
- API의 query.proto 스펙 변경에 따른 코드 수정
> Change query.proto

- config/default.json
- Endpoint 목록에 Dashboard Service 추가
> feat: add endpoint of dashboard service

- src/controllers/add-ons/autocomplete/distinct.ts
- Distinct API 요청 시 Array 형태의 필드는 Distinct를 걸더라도 특정 값만 리턴되는 것이 아닌 Array 내 모든 값이 병합되어 리턴됨
- `search` 필드가 동작하도록 예외 코드 추가
> refactor: refactor distinct API

- src/controllers/config/domain-config/index.ts
- src/routes/config/domain-config.ts
- src/routes/config/index.ts
- `config.DomainConfig` API 추가
> feat: add config.DomainConfig APIs

- deploy/helm/Chart.yaml
- deploy/helm/config/nginx.conf
> build: change nginx.conf

- package-lock.json
- src/lib/grpc-client/index.ts
> refactor: delete channel on gRPC connection failure

- package-lock.json
- src/controllers/statistics/topic/service-account-summary.ts
- Inventory > CloudService 내 Service Account ID 필드 변경에 따른 쿼리 수정
> Fix Statistics Bug

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- Page Schema의 `details` 메타데이터에 Cloud Service Type 지원
> Improve Page Schema

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- Cloud Service로 받아온 `options` 데이터가 `null`일때 예외처리 추가
> fix: fix null bug

- src/controllers/add-ons/autocomplete/distinct.ts
- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- distinct API에 `parameters` 옵션 추가
- page schema의 리턴에 `default_sort` 옵션 추가
> Add API Options

- src/controllers/add-ons/autocomplete/resource.ts
- 리소스 목록을 가져오는 API의 옵션에 `parameters` 추가
> feat: add parameters option to resource API

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
> fix: do not replace all schema data from custom data but only fields

- src/lib/excel/index.ts
- src/lib/excel/type.ts
- src/lib/utils.ts
> feat(excel-export): add logic for key_depth option

- src/controllers/add-ons/autocomplete/config.json
> feat: add cost_analysis.DataSource to autocomplete/config.json

- src/controllers/add-ons/favorite/type.ts
> feat: add cost-analysis favorite type

- config/default.json
- src/lib/excel/index.ts
- src/lib/excel/type.ts
- src/lib/service-client-v2.ts
> feat: add `baseURLV2` to default.json and add `version` param to excel api

- src/controllers/inventory/cloud-service/index.ts
- `inventory.CloudService.list` API에 강제로 Paging 1000개로 제한된 문제를 해결하기 위한 Paginator 개발
- `query.page` Parameter에 어떠한 옵션도 설정되어 있지 않을때만 동작하도록 개선
> refactor: apply paginator to inventory.CloudService.list API

- src/lib/grpc-client/proto/handler.proto
- src/lib/grpc-client/proto/query.proto
> refactor: change default protobuf

- src/controllers/inventory/cloud-service/index.ts
- `inventory.CloudService.list` API에서 Paginator 버그 수정
> fix: fix paginator bug in inventory.CloudService.list API

- src/controllers/inventory/cloud-service/index.ts
- `inventory.CloudService.list` API에서 쿼리 버그 수정
> fix: fix query bug

- src/controllers/add-ons/excel/index.ts
- src/controllers/add-ons/excel/type.ts
> feat: add `data` to `ExcelExportOptions`

- src/controllers/add-ons/recent/type.ts
> fix: add CostAnalysis recent type

- src/controllers/add-ons/autocomplete/config.json
> feat: add `inventory.CloudServiceQuerySet` to autocomplete

- src/lib/error.ts
- 에러 발생 시 리턴 포맷 변경 (`error` -> `detail`)
> feat: change error response format

- src/lib/grpc-client/proto/query.proto
> feat: change query.proto

- src/lib/grpc-client/proto/query.proto
- Query 옵션으로 `unwind` 및 `page` 추가
> feat: add unwind and page option to query

- src/lib/grpc-client/proto/query.proto
- unwind에 `path`와 `filter` 옵션 추가
> feat: add unwind path and filter option to query

- src/controllers/add-ons/page-schema/index.ts
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details_multiple.json
- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- Page Schema API 요청 시 `is_multiple` 옵션 추가
> feat: add is_multiple option to page schema API

- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details_multiple.json
- CloudService의 Multiple Schema에 이름 추가
> feat: add name to multiple schema of cloud service

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- Multiple Schema를 가져올 시 `unwind` 옵션 추가
> feat: add unwind option to multiple schema

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- Cloud Service의 Details Page Schema 요청 시 table 속성에 `unwind` 옵션 추가
> refactor: change table schema in cloud service

- src/controllers/add-ons/page-schema/inventoryServer/index.ts
- 서버의 스키마 요청 시 table type 스펙 변경
> refactor: change table schema in server

- src/lib/grpc-client/proto/query.proto
- Export Query 시 `title` 옵션 추가
> feat: add title option to export query

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- src/controllers/add-ons/page-schema/inventoryServer/index.ts
- Page Schema API에서 Table 정책 변경
> Change Policy in Page Schema

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- src/controllers/add-ons/page-schema/inventoryServer/index.ts
- Page Schema에서 `root_path`가 없을 경우 발생하는 키 버그 수정
> fix: fix key bug in page schema

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- src/controllers/add-ons/page-schema/inventoryServer/index.ts
- add unwind options to table schema
> feat: add unwind options to table schema

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- 다중 선택 테이블 스키마에 reference.resource_id를 기본 정렬로 추가
- 다중 선택 테이블 스키마 수정
> Change Table Schema

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- src/controllers/add-ons/page-schema/inventoryServer/index.ts
- Table Schema의 Field 옵션에 reference 옵션 추가
> feat: add reference option to field in table schema

- src/lib/authentication.ts
- src/lib/grpc-client/index.ts
- src/lib/grpc-client/proto/tag.proto
> fix: fix proto bug

- src/controllers/add-ons/favorite/index.ts
- src/controllers/add-ons/recent/search/index.ts
- src/controllers/add-ons/recent/visit/index.ts
- src/controllers/inventory/cloud-service-type/analyze-cloud-service-types.ts
- src/controllers/inventory/cloud-service/analyze-cloud-services.ts
- src/controllers/monitoring/dashboard/alert-by-project.ts
- src/controllers/monitoring/dashboard/current-project-status.ts
- src/controllers/monitoring/dashboard/daily-alert-history.ts
- src/controllers/monitoring/dashboard/top5-project-activity-alert-details.ts
- src/controllers/monitoring/dashboard/top5-project-activity-list.ts
- src/controllers/statistics/topic/cloud-service-by-region.ts
- src/controllers/statistics/topic/cloud-service-resources.ts
- src/controllers/statistics/topic/daily-cloud-service-summary.ts
- src/controllers/statistics/topic/daily-update-cloud-service.ts
- src/controllers/statistics/topic/phd-events.ts
- src/controllers/statistics/topic/phd-summary.ts
- src/controllers/statistics/topic/power-scheduler-schedules.ts
- src/controllers/statistics/topic/resource-by-region.ts
- src/controllers/statistics/topic/service-account-by-provider.ts
- src/controllers/statistics/topic/service-account-summary.ts
- src/controllers/statistics/topic/top-project.ts
- src/lib/grpc-client/proto/query_v2.proto
> Change Sort and Statistics Query

- src/controllers/add-ons/autocomplete/config.json
- src/controllers/add-ons/autocomplete/resource.ts
- Autocomplete API에서 project 정보 변경
> refactor: change project info in autocomplete API

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- custom widget 메타데이터가 비어 있을 경우 타입 문제 수정
> fix: fix typo

- src/controllers/add-ons/favorite/index.ts
- src/controllers/add-ons/favorite/type.ts
> fix: apply workspace id in favorite api

- src/controllers/add-ons/recent/search/index.ts
- src/controllers/add-ons/recent/type.ts
- src/controllers/add-ons/recent/visit/index.ts
> fix: apply workspace id in recent api

- src/lib/authentication.ts
> refactor: remove verification of jwt

- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
> fix: change the value of created_at label

- src/controllers/add-ons/page-schema/index.ts
- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/details.json
- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/details_multiple.json
- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/search.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/table.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/widget.json
- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- src/controllers/add-ons/page-schema/inventoryServer/admin-schema/details.json
- src/controllers/add-ons/page-schema/inventoryServer/admin-schema/search.json
- src/controllers/add-ons/page-schema/inventoryServer/admin-schema/table.json
- src/controllers/add-ons/page-schema/inventoryServer/admin-schema/widget.json
- src/controllers/add-ons/page-schema/inventoryServer/index.ts
- PageSchema를 가져오는 API에 Admin Mode를 위한 `include_workspace_info` 옵션 필드 추가
> feat: add includeWorkspaceInfo option to page-schema API

- src/controllers/add-ons/autocomplete/config.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details_multiple.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/search.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/search.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json
- Server와 Cloud Service의 Page Schema 정책 변경
- 자동완성에 Autocomplete 추가
> Page Schema 정책 변경

- .github/PULL_REQUEST_TEMPLATE.md
- change pr template to english
> chore: change pr template

- src/lib/logger.ts
> chore: change log format

- src/controllers/identity/trusted-account/index.ts
- src/lib/authentication.ts
- src/lib/excel/redis.ts
- src/routes/identity/index.ts
- src/routes/identity/trusted-account.ts
> feat: add trustedAccount to controllers

- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/details.json
- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/details_multiple.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details_multiple.json
- src/controllers/add-ons/page-schema/inventoryServer/admin-schema/details.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryServer/index.ts
- src/controllers/statistics/topic/service-account-summary.ts
- change queries and metadata using collection_info
- refactor page schema of server
> Refactor Page Schema and Metadata

- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/details.json
- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/details_multiple.json
- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/search.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/admin-schema/table.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details_multiple.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/search.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
- src/controllers/add-ons/page-schema/inventoryServer/admin-schema/details.json
- src/controllers/add-ons/page-schema/inventoryServer/admin-schema/search.json
- src/controllers/add-ons/page-schema/inventoryServer/admin-schema/table.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/search.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json
> feat: change default page schema

- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/details_multiple.json
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/search.json.tmpl
- src/controllers/add-ons/page-schema/inventoryCloudService/default-schema/table.json.tmpl
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/details.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/search.json
- src/controllers/add-ons/page-schema/inventoryServer/default-schema/table.json
- remove workspace field in page schema
> feat: remove workspace field in page schema

- src/controllers/add-ons/page-schema/inventoryCloudService/index.ts
- add `defalut_filter` to table schema
> feat: add default_filter to table schema

- src/controllers/add-ons/autocomplete/config.json
- add resource type for autocomplete
> feat: add resource type for autocomplete

- src/controllers/add-ons/autocomplete/config.json
add alert-manager resources type for autocomplete
> fix: add alert-manager resources type for autocomplete

- src/controllers/alert-manager/alert/index.ts
- src/controllers/alert-manager/escalation-policy/index.ts
- src/controllers/alert-manager/event-rule/index.ts
- src/controllers/alert-manager/note/index.ts
- src/controllers/alert-manager/notification-protocol/index.ts
- src/controllers/alert-manager/service-channel/index.ts
- src/controllers/alert-manager/service/index.ts
- src/controllers/alert-manager/user-channel/index.ts
- src/controllers/alert-manager/user-group-channel/index.ts
- src/controllers/alert-manager/webhook/index.ts
- src/lib/grpc-client/proto/plugin.proto
- src/lib/grpc-client/proto/query_v2.proto
- src/routes/alert-manager/alert.ts
- src/routes/alert-manager/escalation-policy.ts
- src/routes/alert-manager/event-rule.ts
- src/routes/alert-manager/index.ts
- src/routes/alert-manager/note.ts
- src/routes/alert-manager/notification-protocol.ts
- src/routes/alert-manager/service-channel.ts
- src/routes/alert-manager/service.ts
- src/routes/alert-manager/user-channel.ts
- src/routes/alert-manager/user-group-channel.ts
- src/routes/alert-manager/webhook.ts
- src/routes/index.ts
- implement alert manager APIs
> feat: implement alert manager APIs 

- src/controllers/add-ons/autocomplete/config.json
- add cost_analysis Budget auto-complete format
> Add cost_analysis Budget auto-complete format
